JCC = javac

default: Client.class BoardPanel.class ButtonListener.class GamePanel.class HelpPanel.class MainFrame.class MenuPanel.class OptionsPanel.class 

Client.class: Client.java
	$(JCC) Client.java

BoardPanel.class: BoardPanel.java
	$(JCC) BoardPanel.java

ButtonListener.class: ButtonListener.java
	$(JCC) ButtonListener.java

GamePanel.class: GamePanel.java
	$(JCC) GamePanel.java

HelpPanel.class: HelpPanel.java
	$(JCC) HelpPanel.java

MainFrame.class: MainFrame.java
	$(JCC) MainFrame.java

MenuPanel.class: MenuPanel.java
	$(JCC) MenuPanel.java

OptionsPanel.class: OptionsPanel.java
	$(JCC) OptionsPanel.java

clean:
	$(RM) *.class
