JCC = javac

default: App.class BoardPanel.class ButtonListener.class GamePanel.class HelpPanel.class MainFrame.class MenuPanel.class OptionsPanel.class 

App.class: App.java
	$(JCC) App.java

BoardPanel.class: BoardPanel.java
	$(JCC) BoardPanel.java

ButtonListener.class: ButtonListener.java
	$(JCC) ButtonListener.java

GamePanel.class: GamePanel.java
	$(JCC) GamePanel.java

HelpPanel.class: HelpPanel.java
	$(JCC) HelpPanel.java

MainFrame.class: MainFrame.java
	$(JCC) MainFrame.java

MenuPanel.class: MenuPanel.java
	$(JCC) MenuPanel.java

OptionsPanel.class: OptionsPanel.java
	$(JCC) OptionsPanel.java

clean:
	$(RM) *.class
